basePath: /
definitions:
  auth.AdminPasswordUpdate:
    properties:
      password:
        minLength: 6
        type: string
    required:
    - password
    type: object
  auth.AdminUserResponse:
    properties:
      id:
        type: integer
      role:
        type: string
      status:
        type: integer
      username:
        type: string
    type: object
  auth.SigninRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  auth.SigninResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/auth.AdminUserResponse'
    type: object
  auth.SignupRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  auth.WxSigninResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/auth.WxUserResponse'
    type: object
  auth.WxUserResponse:
    properties:
      class:
        type: string
      expire_date:
        type: string
      grade:
        type: string
      id:
        type: integer
      identity:
        type: string
      name:
        type: string
      open_id:
        type: string
      role:
        type: string
      status:
        type: integer
    type: object
  response.ErrorRes:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  response.ListRes:
    properties:
      count:
        type: integer
      data: {}
      page_id:
        type: integer
      page_size:
        type: integer
    type: object
  response.SuccessRes:
    properties:
      data: {}
    type: object
  user.WxUser:
    properties:
      created:
        type: string
      created_by:
        type: string
      id:
        type: integer
      name:
        type: string
      organization_id:
        type: string
      status:
        type: integer
      updated:
        type: string
      updated_by:
        type: string
      wxUser_id:
        type: string
      wxUser_type:
        type: string
    type: object
  user.WxUserNew:
    properties:
      class:
        maxLength: 64
        minLength: 1
        type: string
      expire_date:
        maxLength: 64
        minLength: 1
        type: string
      grade:
        maxLength: 64
        minLength: 1
        type: string
      identity:
        maxLength: 64
        minLength: 1
        type: string
      name:
        maxLength: 64
        minLength: 1
        type: string
      role:
        maxLength: 64
        minLength: 1
        type: string
      status:
        enum:
        - 1
        - 2
        type: integer
    required:
    - expire_date
    - identity
    - name
    - role
    - status
    type: object
  user.WxUserResponse:
    properties:
      name:
        type: string
      organization_id:
        type: string
      status:
        type: integer
      wxUser_id:
        type: string
    type: object
host: 0.0.0.0:8080
info:
  contact:
    email: lxx0103@yahoo.com
    name: Lewis
  description: API for bus-api.
  title: bus-api API
  version: "1.0"
paths:
  /adminusers:
    get:
      consumes:
      - application/json
      operationId: "003"
      parameters:
      - description: 页码
        in: query
        name: page_id
        required: true
        type: integer
      - description: 每页行数（5/10/15/20）
        in: query
        name: page_size
        required: true
        type: integer
      - description: 用户名称
        in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ListRes'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/auth.AdminUserResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 后台用户列表
      tags:
      - 用户管理
  /adminusers/:id:
    get:
      consumes:
      - application/json
      operationId: "004"
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/auth.AdminUserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 根据ID获取后台用户
      tags:
      - 用户管理
  /adminusers/:id/passwords:
    put:
      consumes:
      - application/json
      operationId: "005"
      parameters:
      - description: 用户信息
        in: body
        name: info
        required: true
        schema:
          $ref: '#/definitions/auth.AdminPasswordUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 更新密码
      tags:
      - 用户管理
  /signin:
    post:
      consumes:
      - application/json
      operationId: "001"
      parameters:
      - description: 登录类型
        in: body
        name: signin_info
        required: true
        schema:
          $ref: '#/definitions/auth.SigninRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/auth.SigninResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 登录
      tags:
      - 用户管理
  /users:
    post:
      consumes:
      - application/json
      operationId: "002"
      parameters:
      - description: 登录类型
        in: body
        name: signup_info
        required: true
        schema:
          $ref: '#/definitions/auth.SignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 创建后台用户
      tags:
      - 用户管理
  /wx/signin:
    post:
      consumes:
      - application/json
      operationId: "006"
      parameters:
      - description: 登录类型
        in: body
        name: signin_info
        required: true
        schema:
          $ref: '#/definitions/auth.SigninRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/auth.WxSigninResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 小程序登录
      tags:
      - 小程序管理
  /wxusers:
    get:
      consumes:
      - application/json
      operationId: "301"
      parameters:
      - description: 页码
        in: query
        name: page_id
        required: true
        type: integer
      - description: 每页行数（5/10/15/20）
        in: query
        name: page_size
        required: true
        type: integer
      - description: 姓名
        in: query
        name: name
        type: string
      - description: 班级
        in: query
        name: class
        type: string
      - description: 年级
        in: query
        name: grade
        type: string
      - description: 身份证号
        in: query
        name: identity
        type: string
      - description: 角色（学生，员工）
        in: query
        name: role
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ListRes'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/auth.WxUserResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 小程序用户列表
      tags:
      - 小程序用户管理
    post:
      consumes:
      - application/json
      operationId: "302"
      parameters:
      - description: 小程序用户信息
        in: body
        name: wxUser_info
        required: true
        schema:
          $ref: '#/definitions/user.WxUserNew'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/user.WxUserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 新建小程序用户
      tags:
      - 小程序用户管理
  /wxusers/:id:
    delete:
      consumes:
      - application/json
      operationId: "305"
      parameters:
      - description: 小程序用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 根据ID删除小程序用户
      tags:
      - 小程序用户管理
    get:
      consumes:
      - application/json
      operationId: "304"
      parameters:
      - description: 小程序用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/user.WxUserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 根据ID获取小程序用户
      tags:
      - 小程序用户管理
    put:
      consumes:
      - application/json
      operationId: "303"
      parameters:
      - description: 小程序用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 小程序用户信息
        in: body
        name: wxUser_info
        required: true
        schema:
          $ref: '#/definitions/user.WxUserNew'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/user.WxUser'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 根据ID更新小程序用户
      tags:
      - 小程序用户管理
  /wxusers/batch:
    post:
      consumes:
      - application/json
      operationId: "61"
      parameters:
      - description: 上传文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessRes'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorRes'
      summary: 批量导入微信用户
      tags:
      - 小程序用户管理
swagger: "2.0"
